default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost
  port: 8889
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

development:
  <<: *default
  database: math_trainer_dev

test:
  <<: *default
  database: math_trainer_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
