default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: demouser
  password: dummypassword
  host: localhost
  port: 5432

development:
  <<: *default
  database: math_trainer_dev

test:
  <<: *default
  database: math_trainer_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
